version: '3'
services:
  postgres:
    image: arminc/clair-db

  clair:
    image: arminc/clair-local-scan:v2.0.8_0ed98e9ead65a51ba53f7cc53fa5e80c92169207
    volumes:
      - ./clair-scanner/wait-for:/app/wait-for
    entrypoint: /app/wait-for postgres:5432 -- /clair -config=/config/config.yaml
    ports:
      - 6060:6060

  clair-scanner:
    image: hpcsc/clair-scanner:0.1.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: 
      - ./wait-for
      - clair:6060
      - --
      - clair-scanner
      - --ip
      - clair-scanner
      - -c
      - http://clair:6060
      - ${IMAGE_TO_SCAN}

